name: Compilation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build with ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt-get install -y ${{ matrix.compiler }} cmake make libdrm-dev libgbm-dev libfreetype6-dev libharfbuzz-dev nasm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Fetchcontent
        id: cache-fetchcontent
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/build/_deps/*-src
          key: ${{ runner.os }}-${{ matrix.compiler }}-fetchcontent-${{ hashFiles('**/yoyoeditor/CMakeLists.txt') }}

      - name: Configure with CMake
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          CC=${{ matrix.compiler }} cmake -DBUILD_LUA_RUNTIME=OFF -DSDL_UNIX_CONSOLE_BUILD=ON -DZOOGIES_DEVELOPMENT_BUILD=TRUE ..
      
      - name: Build with ${{ matrix.compiler }}
        run: |
          cd ${{ github.workspace }}/build
          make -j$(nproc)